//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REKTDICEGAME
{
    using System;
    using System.Collections.Generic;
    
    public partial class rankingStorage
    {
        public Nullable<int> points { get; set; }
        public Nullable<int> attempts { get; set; }
        public string username { get; set; }
        public int id { get; set; }
    }
}
